//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWorkSalary.Resources.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWorkSalary.Resources.Resx.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓  AKTIVE.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Work.
        /// </summary>
        internal static string ActiveJob {
            get {
                return ResourceManager.GetString("ActiveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your first job to start using the app..
        /// </summary>
        internal static string AddFirstJobText {
            get {
                return ResourceManager.GetString("AddFirstJobText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✚  Add.
        /// </summary>
        internal static string AddJob {
            get {
                return ResourceManager.GetString("AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 Basic information.
        /// </summary>
        internal static string AddJobPage_BasicInfo {
            get {
                return ResourceManager.GetString("AddJobPage_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country *.
        /// </summary>
        internal static string AddJobPage_Country {
            get {
                return ResourceManager.GetString("AddJobPage_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Select the country where the job is performed….
        /// </summary>
        internal static string AddJobPage_CountryTip {
            get {
                return ResourceManager.GetString("AddJobPage_CountryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment start date *.
        /// </summary>
        internal static string AddJobPage_EmploymentDate {
            get {
                return ResourceManager.GetString("AddJobPage_EmploymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment type.
        /// </summary>
        internal static string AddJobPage_EmploymentType {
            get {
                return ResourceManager.GetString("AddJobPage_EmploymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected hours / month.
        /// </summary>
        internal static string AddJobPage_ExpectedHours {
            get {
                return ResourceManager.GetString("AddJobPage_ExpectedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly rate.
        /// </summary>
        internal static string AddJobPage_HourlyRate {
            get {
                return ResourceManager.GetString("AddJobPage_HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title *.
        /// </summary>
        internal static string AddJobPage_JobTitle {
            get {
                return ResourceManager.GetString("AddJobPage_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Nurse.
        /// </summary>
        internal static string AddJobPage_JobTitle_Placeholder {
            get {
                return ResourceManager.GetString("AddJobPage_JobTitle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly salary.
        /// </summary>
        internal static string AddJobPage_MonthlySalary {
            get {
                return ResourceManager.GetString("AddJobPage_MonthlySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💰 Salary information.
        /// </summary>
        internal static string AddJobPage_SalarySection {
            get {
                return ResourceManager.GetString("AddJobPage_SalarySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary type.
        /// </summary>
        internal static string AddJobPage_SalaryType {
            get {
                return ResourceManager.GetString("AddJobPage_SalaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved vacation days now.
        /// </summary>
        internal static string AddJobPage_SavedVacation {
            get {
                return ResourceManager.GetString("AddJobPage_SavedVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Enter your saved days….
        /// </summary>
        internal static string AddJobPage_SavedVacationTip {
            get {
                return ResourceManager.GetString("AddJobPage_SavedVacationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax rate (%).
        /// </summary>
        internal static string AddJobPage_TaxRate {
            get {
                return ResourceManager.GetString("AddJobPage_TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏛️ Tax information.
        /// </summary>
        internal static string AddJobPage_TaxSection {
            get {
                return ResourceManager.GetString("AddJobPage_TaxSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Tip: Check your latest salary spec.
        /// </summary>
        internal static string AddJobPage_TaxTip {
            get {
                return ResourceManager.GetString("AddJobPage_TaxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ️ As a temp employee, you are usually not entitled to paid vacation leave.
        ///Instead, you receive a vacation allowance that must be at least 12% of your earned salary.
        ///It is paid either monthly together with your salary or as a lump sum
        ///when employment ends (no later than one month afterwards)..
        /// </summary>
        internal static string AddJobPage_TemporaryInfo {
            get {
                return ResourceManager.GetString("AddJobPage_TemporaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new job.
        /// </summary>
        internal static string AddJobPage_Title {
            get {
                return ResourceManager.GetString("AddJobPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation days / year.
        /// </summary>
        internal static string AddJobPage_VacationDays {
            get {
                return ResourceManager.GetString("AddJobPage_VacationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏖️ Vacation information.
        /// </summary>
        internal static string AddJobPage_VacationSection {
            get {
                return ResourceManager.GetString("AddJobPage_VacationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace *.
        /// </summary>
        internal static string AddJobPage_Workplace {
            get {
                return ResourceManager.GetString("AddJobPage_Workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Municipality.
        /// </summary>
        internal static string AddJobPage_Workplace_Placeholder {
            get {
                return ResourceManager.GetString("AddJobPage_Workplace_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add Unsocial Hours Rule.
        /// </summary>
        internal static string AddOBRule {
            get {
                return ResourceManager.GetString("AddOBRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔧 App Settings.
        /// </summary>
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not switch job: {0}.
        /// </summary>
        internal static string ChangeJobFailedMessageFormat {
            get {
                return ResourceManager.GetString("ChangeJobFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme enabled.
        /// </summary>
        internal static string DarkThemeActive {
            get {
                return ResourceManager.GetString("DarkThemeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are deleting the active job. Select another job as active first, or delete all jobs..
        /// </summary>
        internal static string DeleteActiveJobMessage {
            get {
                return ResourceManager.GetString("DeleteActiveJobMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete the job: {0}.
        /// </summary>
        internal static string DeleteJobFailedMessageFormat {
            get {
                return ResourceManager.GetString("DeleteJobFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete &apos;{0}&apos; from {1}? This will delete all related shifts and data..
        /// </summary>
        internal static string DeleteJobMessageFormat {
            get {
                return ResourceManager.GetString("DeleteJobMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete job.
        /// </summary>
        internal static string DeleteJobTitle {
            get {
                return ResourceManager.GetString("DeleteJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are deleting your LAST job &apos;{0}&apos;.  You will need to create a new job to use the app. Continue?.
        /// </summary>
        internal static string DeleteLastJobMessageFormat {
            get {
                return ResourceManager.GetString("DeleteLastJobMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Delete last job.
        /// </summary>
        internal static string DeleteLastJobTitle {
            get {
                return ResourceManager.GetString("DeleteLastJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete the rule.
        /// </summary>
        internal static string DeleteOBRateFailedMessage {
            get {
                return ResourceManager.GetString("DeleteOBRateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteOBRateMessageFormat {
            get {
                return ResourceManager.GetString("DeleteOBRateMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete rule.
        /// </summary>
        internal static string DeleteOBRateTitle {
            get {
                return ResourceManager.GetString("DeleteOBRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️  Edit.
        /// </summary>
        internal static string EditJob {
            get {
                return ResourceManager.GetString("EditJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exactly on schedule.
        /// </summary>
        internal static string ExactSchedule {
            get {
                return ResourceManager.GetString("ExactSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours to hour bank.
        /// </summary>
        internal static string HoursToBank {
            get {
                return ResourceManager.GetString("HoursToBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed to: {0}.
        /// </summary>
        internal static string JobChangedMessageFormat {
            get {
                return ResourceManager.GetString("JobChangedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job has been deleted..
        /// </summary>
        internal static string JobDeletedSuccessMessage {
            get {
                return ResourceManager.GetString("JobDeletedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string JobDeletedTitle {
            get {
                return ResourceManager.GetString("JobDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        internal static string LanguageSwedish {
            get {
                return ResourceManager.GetString("LanguageSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last job deleted. You can create a new job via the &apos;Add&apos; button..
        /// </summary>
        internal static string LastJobDeletedSuccessMessage {
            get {
                return ResourceManager.GetString("LastJobDeletedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright appearance enabled.
        /// </summary>
        internal static string LightThemeActive {
            get {
                return ResourceManager.GetString("LightThemeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💼 My Jobs.
        /// </summary>
        internal static string MyJobs {
            get {
                return ResourceManager.GetString("MyJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active job.
        /// </summary>
        internal static string NoActiveJob {
            get {
                return ResourceManager.GetString("NoActiveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs registered.
        /// </summary>
        internal static string NoJobsRegistered {
            get {
                return ResourceManager.GetString("NoJobsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        internal static string OBCategory_Evening {
            get {
                return ResourceManager.GetString("OBCategory_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string OBCategory_Night {
            get {
                return ResourceManager.GetString("OBCategory_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        internal static string OBCategory_Weekend {
            get {
                return ResourceManager.GetString("OBCategory_Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏰ Unsocial hours settings.
        /// </summary>
        internal static string OBSettings {
            get {
                return ResourceManager.GetString("OBSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Tip: Check your latest salary spec to see which Inconvenient Working Hours allowances apply to you. Configure unsocial hours rules so that salary calculations are accurate..
        /// </summary>
        internal static string OBTips {
            get {
                return ResourceManager.GetString("OBTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Swipe left to delete a job.
        /// </summary>
        internal static string SwipeDeleteJobHint {
            get {
                return ResourceManager.GetString("SwipeDeleteJobHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Swipe left to delete a rule.
        /// </summary>
        internal static string SwipeDeleteOBHint {
            get {
                return ResourceManager.GetString("SwipeDeleteOBHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save theme setting.
        /// </summary>
        internal static string ThemeSaveErrorMessage {
            get {
                return ResourceManager.GetString("ThemeSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your payroll app!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
