//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWorkSalary.Resources.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWorkSalary.Resources.Resx.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓  AKTIVE.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Work.
        /// </summary>
        internal static string ActiveJob {
            get {
                return ResourceManager.GetString("ActiveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your first job to start using the app..
        /// </summary>
        internal static string AddFirstJobText {
            get {
                return ResourceManager.GetString("AddFirstJobText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✚  Add.
        /// </summary>
        internal static string AddJob {
            get {
                return ResourceManager.GetString("AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 Basic information.
        /// </summary>
        internal static string AddJobPage_BasicInfo {
            get {
                return ResourceManager.GetString("AddJobPage_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country *.
        /// </summary>
        internal static string AddJobPage_Country {
            get {
                return ResourceManager.GetString("AddJobPage_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Select the country where the job is performed….
        /// </summary>
        internal static string AddJobPage_CountryTip {
            get {
                return ResourceManager.GetString("AddJobPage_CountryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string AddJobPage_Currency {
            get {
                return ResourceManager.GetString("AddJobPage_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the currency you get paid in..
        /// </summary>
        internal static string AddJobPage_CurrencyTip {
            get {
                return ResourceManager.GetString("AddJobPage_CurrencyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment start date *.
        /// </summary>
        internal static string AddJobPage_EmploymentDate {
            get {
                return ResourceManager.GetString("AddJobPage_EmploymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment type.
        /// </summary>
        internal static string AddJobPage_EmploymentType {
            get {
                return ResourceManager.GetString("AddJobPage_EmploymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected hours / month.
        /// </summary>
        internal static string AddJobPage_ExpectedHours {
            get {
                return ResourceManager.GetString("AddJobPage_ExpectedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly rate.
        /// </summary>
        internal static string AddJobPage_HourlyRate {
            get {
                return ResourceManager.GetString("AddJobPage_HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title *.
        /// </summary>
        internal static string AddJobPage_JobTitle {
            get {
                return ResourceManager.GetString("AddJobPage_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Nurse.
        /// </summary>
        internal static string AddJobPage_JobTitle_Placeholder {
            get {
                return ResourceManager.GetString("AddJobPage_JobTitle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly salary.
        /// </summary>
        internal static string AddJobPage_MonthlySalary {
            get {
                return ResourceManager.GetString("AddJobPage_MonthlySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💰 Salary information.
        /// </summary>
        internal static string AddJobPage_SalarySection {
            get {
                return ResourceManager.GetString("AddJobPage_SalarySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary type.
        /// </summary>
        internal static string AddJobPage_SalaryType {
            get {
                return ResourceManager.GetString("AddJobPage_SalaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved vacation days now.
        /// </summary>
        internal static string AddJobPage_SavedVacation {
            get {
                return ResourceManager.GetString("AddJobPage_SavedVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Enter your saved days….
        /// </summary>
        internal static string AddJobPage_SavedVacationTip {
            get {
                return ResourceManager.GetString("AddJobPage_SavedVacationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax rate (%).
        /// </summary>
        internal static string AddJobPage_TaxRate {
            get {
                return ResourceManager.GetString("AddJobPage_TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏛️ Tax information.
        /// </summary>
        internal static string AddJobPage_TaxSection {
            get {
                return ResourceManager.GetString("AddJobPage_TaxSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Tip: Check your latest salary spec.
        /// </summary>
        internal static string AddJobPage_TaxTip {
            get {
                return ResourceManager.GetString("AddJobPage_TaxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ️ As a temp employee, you are usually not entitled to paid vacation leave.
        ///Instead, you receive a vacation allowance that must be at least 12% of your earned salary.
        ///It is paid either monthly together with your salary or as a lump sum
        ///when employment ends (no later than one month afterwards)..
        /// </summary>
        internal static string AddJobPage_TemporaryInfo {
            get {
                return ResourceManager.GetString("AddJobPage_TemporaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new job.
        /// </summary>
        internal static string AddJobPage_Title {
            get {
                return ResourceManager.GetString("AddJobPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation days / year.
        /// </summary>
        internal static string AddJobPage_VacationDays {
            get {
                return ResourceManager.GetString("AddJobPage_VacationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏖️ Vacation information.
        /// </summary>
        internal static string AddJobPage_VacationSection {
            get {
                return ResourceManager.GetString("AddJobPage_VacationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace *.
        /// </summary>
        internal static string AddJobPage_Workplace {
            get {
                return ResourceManager.GetString("AddJobPage_Workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Municipality.
        /// </summary>
        internal static string AddJobPage_Workplace_Placeholder {
            get {
                return ResourceManager.GetString("AddJobPage_Workplace_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add Unsocial Hours Rule.
        /// </summary>
        internal static string AddOBRule {
            get {
                return ResourceManager.GetString("AddOBRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add Shift.
        /// </summary>
        internal static string AddShift {
            get {
                return ResourceManager.GetString("AddShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔧 App Settings.
        /// </summary>
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 Basic information.
        /// </summary>
        internal static string BasicInfo_SectionTitle {
            get {
                return ResourceManager.GetString("BasicInfo_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💾 Save changes.
        /// </summary>
        internal static string Button_SaveChanges {
            get {
                return ResourceManager.GetString("Button_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Salary.
        /// </summary>
        internal static string CalculateSalary {
            get {
                return ResourceManager.GetString("CalculateSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        internal static string Category_Evening {
            get {
                return ResourceManager.GetString("Category_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Holiday.
        /// </summary>
        internal static string Category_Holiday {
            get {
                return ResourceManager.GetString("Category_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string Category_Night {
            get {
                return ResourceManager.GetString("Category_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        internal static string Category_Placeholder {
            get {
                return ResourceManager.GetString("Category_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        internal static string Category_Weekend {
            get {
                return ResourceManager.GetString("Category_Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend Extra.
        /// </summary>
        internal static string Category_WeekendExtra {
            get {
                return ResourceManager.GetString("Category_WeekendExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not switch job: {0}.
        /// </summary>
        internal static string ChangeJobFailedMessageFormat {
            get {
                return ResourceManager.GetString("ChangeJobFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        internal static string Country_Denmark {
            get {
                return ResourceManager.GetString("Country_Denmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland.
        /// </summary>
        internal static string Country_Finland {
            get {
                return ResourceManager.GetString("Country_Finland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        internal static string Country_France {
            get {
                return ResourceManager.GetString("Country_France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        internal static string Country_Ireland {
            get {
                return ResourceManager.GetString("Country_Ireland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country_Label {
            get {
                return ResourceManager.GetString("Country_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        internal static string Country_Norway {
            get {
                return ResourceManager.GetString("Country_Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        internal static string Country_Sweden {
            get {
                return ResourceManager.GetString("Country_Sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first job.
        /// </summary>
        internal static string CreateFirstJob {
            get {
                return ResourceManager.GetString("CreateFirstJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:C}.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish krone (DKK).
        /// </summary>
        internal static string Currency_DKK {
            get {
                return ResourceManager.GetString("Currency_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro (EUR).
        /// </summary>
        internal static string Currency_EUR {
            get {
                return ResourceManager.GetString("Currency_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency_Label {
            get {
                return ResourceManager.GetString("Currency_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian krone (NOK).
        /// </summary>
        internal static string Currency_NOK {
            get {
                return ResourceManager.GetString("Currency_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish zloty (PLN).
        /// </summary>
        internal static string Currency_PLN {
            get {
                return ResourceManager.GetString("Currency_PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish kronor (SEK).
        /// </summary>
        internal static string Currency_SEK {
            get {
                return ResourceManager.GetString("Currency_SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Dollar (USD).
        /// </summary>
        internal static string Currency_USD {
            get {
                return ResourceManager.GetString("Currency_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MMMM yyyy}.
        /// </summary>
        internal static string CurrentMonthYear {
            get {
                return ResourceManager.GetString("CurrentMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme enabled.
        /// </summary>
        internal static string DarkThemeActive {
            get {
                return ResourceManager.GetString("DarkThemeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are deleting the active job. Select another job as active first, or delete all jobs..
        /// </summary>
        internal static string DeleteActiveJobMessage {
            get {
                return ResourceManager.GetString("DeleteActiveJobMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete the job: {0}.
        /// </summary>
        internal static string DeleteJobFailedMessageFormat {
            get {
                return ResourceManager.GetString("DeleteJobFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete &apos;{0}&apos; from {1}? This will delete all related shifts and data..
        /// </summary>
        internal static string DeleteJobMessageFormat {
            get {
                return ResourceManager.GetString("DeleteJobMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete job.
        /// </summary>
        internal static string DeleteJobTitle {
            get {
                return ResourceManager.GetString("DeleteJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are deleting your LAST job &apos;{0}&apos;.  You will need to create a new job to use the app. Continue?.
        /// </summary>
        internal static string DeleteLastJobMessageFormat {
            get {
                return ResourceManager.GetString("DeleteLastJobMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Delete last job.
        /// </summary>
        internal static string DeleteLastJobTitle {
            get {
                return ResourceManager.GetString("DeleteLastJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete the rule.
        /// </summary>
        internal static string DeleteOBRateFailedMessage {
            get {
                return ResourceManager.GetString("DeleteOBRateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteOBRateMessageFormat {
            get {
                return ResourceManager.GetString("DeleteOBRateMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete rule.
        /// </summary>
        internal static string DeleteOBRateTitle {
            get {
                return ResourceManager.GetString("DeleteOBRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Dialog_ErrorTitle {
            get {
                return ResourceManager.GetString("Dialog_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job has been saved!.
        /// </summary>
        internal static string Dialog_JobSavedMessage {
            get {
                return ResourceManager.GetString("Dialog_JobSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the job: {0}.
        /// </summary>
        internal static string Dialog_JobSaveFailedMessageFormat {
            get {
                return ResourceManager.GetString("Dialog_JobSaveFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Dialog_Ok {
            get {
                return ResourceManager.GetString("Dialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all required fields.
        /// </summary>
        internal static string Dialog_RequiredFieldsMessage {
            get {
                return ResourceManager.GetString("Dialog_RequiredFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Dialog_SuccessTitle {
            get {
                return ResourceManager.GetString("Dialog_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned.
        /// </summary>
        internal static string Earned {
            get {
                return ResourceManager.GetString("Earned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️  Edit.
        /// </summary>
        internal static string EditJob {
            get {
                return ResourceManager.GetString("EditJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel? Changes will not be saved..
        /// </summary>
        internal static string EditJob_CancelMessage {
            get {
                return ResourceManager.GetString("EditJob_CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, continue.
        /// </summary>
        internal static string EditJob_CancelNo {
            get {
                return ResourceManager.GetString("EditJob_CancelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EditJob_CancelTitle {
            get {
                return ResourceManager.GetString("EditJob_CancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, cancel.
        /// </summary>
        internal static string EditJob_CancelYes {
            get {
                return ResourceManager.GetString("EditJob_CancelYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update the job: {0}.
        /// </summary>
        internal static string EditJob_ErrorMessage {
            get {
                return ResourceManager.GetString("EditJob_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string EditJob_ErrorTitle {
            get {
                return ResourceManager.GetString("EditJob_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️  Edit job.
        /// </summary>
        internal static string EditJob_Header {
            get {
                return ResourceManager.GetString("EditJob_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string EditJob_Ok {
            get {
                return ResourceManager.GetString("EditJob_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job has been updated!.
        /// </summary>
        internal static string EditJob_SuccessMessage {
            get {
                return ResourceManager.GetString("EditJob_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string EditJob_SuccessTitle {
            get {
                return ResourceManager.GetString("EditJob_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit job.
        /// </summary>
        internal static string EditJob_Title {
            get {
                return ResourceManager.GetString("EditJob_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment date *.
        /// </summary>
        internal static string EmploymentDate_Label {
            get {
                return ResourceManager.GetString("EmploymentDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string EmploymentType_Default {
            get {
                return ResourceManager.GetString("EmploymentType_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment type.
        /// </summary>
        internal static string EmploymentType_Label {
            get {
                return ResourceManager.GetString("EmploymentType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent.
        /// </summary>
        internal static string EmploymentType_Permanent {
            get {
                return ResourceManager.GetString("EmploymentType_Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary / On-call.
        /// </summary>
        internal static string EmploymentType_Temporary {
            get {
                return ResourceManager.GetString("EmploymentType_Temporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exactly on schedule.
        /// </summary>
        internal static string ExactSchedule {
            get {
                return ResourceManager.GetString("ExactSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected hours per month.
        /// </summary>
        internal static string ExpectedHours_Label {
            get {
                return ResourceManager.GetString("ExpectedHours_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 165.
        /// </summary>
        internal static string ExpectedHours_Placeholder {
            get {
                return ResourceManager.GetString("ExpectedHours_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        internal static string FlexBalanced {
            get {
                return ResourceManager.GetString("FlexBalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours debt.
        /// </summary>
        internal static string FlexNegative {
            get {
                return ResourceManager.GetString("FlexNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} hours of availability.
        /// </summary>
        internal static string FlexPositive {
            get {
                return ResourceManager.GetString("FlexPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flex Time .
        /// </summary>
        internal static string FlexTime {
            get {
                return ResourceManager.GetString("FlexTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Hours remaining/over monthly goal.
        /// </summary>
        internal static string FlexTimeTooltip {
            get {
                return ResourceManager.GetString("FlexTimeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started by creating your first job.
        /// </summary>
        internal static string GetStartedPrompt {
            get {
                return ResourceManager.GetString("GetStartedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/h.
        /// </summary>
        internal static string HourlyRate {
            get {
                return ResourceManager.GetString("HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly rate .
        /// </summary>
        internal static string HourlySalary_Label {
            get {
                return ResourceManager.GetString("HourlySalary_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 185.
        /// </summary>
        internal static string HourlySalary_Placeholder {
            get {
                return ResourceManager.GetString("HourlySalary_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly wage.
        /// </summary>
        internal static string HourlyWage {
            get {
                return ResourceManager.GetString("HourlyWage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string HoursAbbreviation {
            get {
                return ResourceManager.GetString("HoursAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours credit.
        /// </summary>
        internal static string HoursCredit {
            get {
                return ResourceManager.GetString("HoursCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours owed.
        /// </summary>
        internal static string HoursOwed {
            get {
                return ResourceManager.GetString("HoursOwed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours/month.
        /// </summary>
        internal static string HoursPerMonth {
            get {
                return ResourceManager.GetString("HoursPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string HoursText {
            get {
                return ResourceManager.GetString("HoursText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours to hour bank.
        /// </summary>
        internal static string HoursToBank {
            get {
                return ResourceManager.GetString("HoursToBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Worked.
        /// </summary>
        internal static string HoursWorked {
            get {
                return ResourceManager.GetString("HoursWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved vacation days right now.
        /// </summary>
        internal static string InitialVacation_Label {
            get {
                return ResourceManager.GetString("InitialVacation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 12.5.
        /// </summary>
        internal static string InitialVacation_Placeholder {
            get {
                return ResourceManager.GetString("InitialVacation_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed to: {0}.
        /// </summary>
        internal static string JobChangedMessageFormat {
            get {
                return ResourceManager.GetString("JobChangedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job has been deleted..
        /// </summary>
        internal static string JobDeletedSuccessMessage {
            get {
                return ResourceManager.GetString("JobDeletedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string JobDeletedTitle {
            get {
                return ResourceManager.GetString("JobDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title *.
        /// </summary>
        internal static string JobTitle_Label {
            get {
                return ResourceManager.GetString("JobTitle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Nursing assistant.
        /// </summary>
        internal static string JobTitle_Placeholder {
            get {
                return ResourceManager.GetString("JobTitle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        internal static string LanguageSwedish {
            get {
                return ResourceManager.GetString("LanguageSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last job deleted. You can create a new job via the &apos;Add&apos; button..
        /// </summary>
        internal static string LastJobDeletedSuccessMessage {
            get {
                return ResourceManager.GetString("LastJobDeletedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright appearance enabled.
        /// </summary>
        internal static string LightThemeActive {
            get {
                return ResourceManager.GetString("LightThemeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced this month.
        /// </summary>
        internal static string MonthlyBalanced {
            get {
                return ResourceManager.GetString("MonthlyBalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly goal reached!.
        /// </summary>
        internal static string MonthlyGoalReached {
            get {
                return ResourceManager.GetString("MonthlyGoalReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours this month.
        /// </summary>
        internal static string MonthlyNegative {
            get {
                return ResourceManager.GetString("MonthlyNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} hours this month.
        /// </summary>
        internal static string MonthlyPositive {
            get {
                return ResourceManager.GetString("MonthlyPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly salary.
        /// </summary>
        internal static string MonthlySalary {
            get {
                return ResourceManager.GetString("MonthlySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly salary .
        /// </summary>
        internal static string MonthlySalary_Label {
            get {
                return ResourceManager.GetString("MonthlySalary_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 28500.
        /// </summary>
        internal static string MonthlySalary_Placeholder {
            get {
                return ResourceManager.GetString("MonthlySalary_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Statistics.
        /// </summary>
        internal static string MonthlyStats {
            get {
                return ResourceManager.GetString("MonthlyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💼 My Jobs.
        /// </summary>
        internal static string MyJobs {
            get {
                return ResourceManager.GetString("MyJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active job.
        /// </summary>
        internal static string NoActiveJob {
            get {
                return ResourceManager.GetString("NoActiveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝.
        /// </summary>
        internal static string NoActivitiesIcon {
            get {
                return ResourceManager.GetString("NoActivitiesIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your first work shift!.
        /// </summary>
        internal static string NoActivitiesMessage {
            get {
                return ResourceManager.GetString("NoActivitiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activities yet.
        /// </summary>
        internal static string NoActivitiesTitle {
            get {
                return ResourceManager.GetString("NoActivitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No flex time.
        /// </summary>
        internal static string NoFlexTime {
            get {
                return ResourceManager.GetString("NoFlexTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No job configured.
        /// </summary>
        internal static string NoJobSetup {
            get {
                return ResourceManager.GetString("NoJobSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs registered.
        /// </summary>
        internal static string NoJobsRegistered {
            get {
                return ResourceManager.GetString("NoJobsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No loss).
        /// </summary>
        internal static string NoLoss {
            get {
                return ResourceManager.GetString("NoLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shifts recorded this month.
        /// </summary>
        internal static string NoShiftsThisMonth {
            get {
                return ResourceManager.GetString("NoShiftsThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        internal static string OBCategory_Evening {
            get {
                return ResourceManager.GetString("OBCategory_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string OBCategory_Night {
            get {
                return ResourceManager.GetString("OBCategory_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        internal static string OBCategory_Weekend {
            get {
                return ResourceManager.GetString("OBCategory_Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsocial Hours.
        /// </summary>
        internal static string ObHoursText {
            get {
                return ResourceManager.GetString("ObHoursText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏷️ Category.
        /// </summary>
        internal static string OBRule_Category_Label {
            get {
                return ResourceManager.GetString("OBRule_Category_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Applies on these days.
        /// </summary>
        internal static string OBRule_Days_Label {
            get {
                return ResourceManager.GetString("OBRule_Days_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string OBRule_Friday {
            get {
                return ResourceManager.GetString("OBRule_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        internal static string OBRule_From_Label {
            get {
                return ResourceManager.GetString("OBRule_From_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        internal static string OBRule_Holidays {
            get {
                return ResourceManager.GetString("OBRule_Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string OBRule_Monday {
            get {
                return ResourceManager.GetString("OBRule_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 Unsocial Hours Name.
        /// </summary>
        internal static string OBRule_Name_Label {
            get {
                return ResourceManager.GetString("OBRule_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. “Evening unsocial hours (weekdays)”.
        /// </summary>
        internal static string OBRule_Name_Placeholder {
            get {
                return ResourceManager.GetString("OBRule_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💰 Pay per hour.
        /// </summary>
        internal static string OBRule_Rate_Label {
            get {
                return ResourceManager.GetString("OBRule_Rate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 56.70.
        /// </summary>
        internal static string OBRule_Rate_Placeholder {
            get {
                return ResourceManager.GetString("OBRule_Rate_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter pay per hour (including base + unsocial hours bonus).
        /// </summary>
        internal static string OBRule_Rate_Tip {
            get {
                return ResourceManager.GetString("OBRule_Rate_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string OBRule_Saturday {
            get {
                return ResourceManager.GetString("OBRule_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💾 Save Unsocial Hours Rule.
        /// </summary>
        internal static string OBRule_Save_Button {
            get {
                return ResourceManager.GetString("OBRule_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string OBRule_SelectAll {
            get {
                return ResourceManager.GetString("OBRule_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekdays.
        /// </summary>
        internal static string OBRule_SelectWeekdays {
            get {
                return ResourceManager.GetString("OBRule_SelectWeekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekends.
        /// </summary>
        internal static string OBRule_SelectWeekends {
            get {
                return ResourceManager.GetString("OBRule_SelectWeekends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string OBRule_Sunday {
            get {
                return ResourceManager.GetString("OBRule_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string OBRule_Thursday {
            get {
                return ResourceManager.GetString("OBRule_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏰ Time Period.
        /// </summary>
        internal static string OBRule_TimeSection_Label {
            get {
                return ResourceManager.GetString("OBRule_TimeSection_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Unsocial Hours Rule.
        /// </summary>
        internal static string OBRule_Title {
            get {
                return ResourceManager.GetString("OBRule_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        internal static string OBRule_To_Label {
            get {
                return ResourceManager.GetString("OBRule_To_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string OBRule_Tuesday {
            get {
                return ResourceManager.GetString("OBRule_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string OBRule_Wednesday {
            get {
                return ResourceManager.GetString("OBRule_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏰ Unsocial hours settings.
        /// </summary>
        internal static string OBSettings {
            get {
                return ResourceManager.GetString("OBSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Tip: Check your latest salary spec to see which Inconvenient Working Hours allowances apply to you. Configure unsocial hours rules so that salary calculations are accurate..
        /// </summary>
        internal static string OBTips {
            get {
                return ResourceManager.GetString("OBTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-call.
        /// </summary>
        internal static string OnCall {
            get {
                return ResourceManager.GetString("OnCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  📞.
        /// </summary>
        internal static string OnCallIcon {
            get {
                return ResourceManager.GetString("OnCallIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-call.
        /// </summary>
        internal static string OnCallLabel {
            get {
                return ResourceManager.GetString("OnCallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1 day).
        /// </summary>
        internal static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime.
        /// </summary>
        internal static string Overtime {
            get {
                return ResourceManager.GetString("Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €/hour.
        /// </summary>
        internal static string PerHour {
            get {
                return ResourceManager.GetString("PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €/month.
        /// </summary>
        internal static string PerMonth {
            get {
                return ResourceManager.GetString("PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Actions.
        /// </summary>
        internal static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Register work time or view salary reports.
        /// </summary>
        internal static string QuickActionsTooltip {
            get {
                return ResourceManager.GetString("QuickActionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activities .
        /// </summary>
        internal static string RecentActivities {
            get {
                return ResourceManager.GetString("RecentActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💰 Salary information.
        /// </summary>
        internal static string Salary_SectionTitle {
            get {
                return ResourceManager.GetString("Salary_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary not specified.
        /// </summary>
        internal static string SalaryNotSpecified {
            get {
                return ResourceManager.GetString("SalaryNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly rate.
        /// </summary>
        internal static string SalaryType_Hourly {
            get {
                return ResourceManager.GetString("SalaryType_Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary type.
        /// </summary>
        internal static string SalaryType_Label {
            get {
                return ResourceManager.GetString("SalaryType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly salary.
        /// </summary>
        internal static string SalaryType_Monthly {
            get {
                return ResourceManager.GetString("SalaryType_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Type.
        /// </summary>
        internal static string SalaryTypeInfo {
            get {
                return ResourceManager.GetString("SalaryTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save unsocial hours rule: {0}.
        /// </summary>
        internal static string Save_Error_Message {
            get {
                return ResourceManager.GetString("Save_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Save_Error_Title {
            get {
                return ResourceManager.GetString("Save_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsocial hours rule &apos;{0}&apos; has been saved..
        /// </summary>
        internal static string Save_Success_Message {
            get {
                return ResourceManager.GetString("Save_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        internal static string Save_Success_Title {
            get {
                return ResourceManager.GetString("Save_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts.
        /// </summary>
        internal static string Shifts {
            get {
                return ResourceManager.GetString("Shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick day.
        /// </summary>
        internal static string SickDay {
            get {
                return ResourceManager.GetString("SickDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick day (1 day) .
        /// </summary>
        internal static string SickDayFull {
            get {
                return ResourceManager.GetString("SickDayFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially sick.
        /// </summary>
        internal static string SickDayPartial {
            get {
                return ResourceManager.GetString("SickDayPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick Leave.
        /// </summary>
        internal static string SickLeave {
            get {
                return ResourceManager.GetString("SickLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏥.
        /// </summary>
        internal static string SickLeaveIcon {
            get {
                return ResourceManager.GetString("SickLeaveIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick on day off.
        /// </summary>
        internal static string SickOnDayOff {
            get {
                return ResourceManager.GetString("SickOnDayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Swipe left to delete a job.
        /// </summary>
        internal static string SwipeDeleteJobHint {
            get {
                return ResourceManager.GetString("SwipeDeleteJobHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Swipe left to delete a rule.
        /// </summary>
        internal static string SwipeDeleteOBHint {
            get {
                return ResourceManager.GetString("SwipeDeleteOBHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏛️ Tax information.
        /// </summary>
        internal static string Tax_SectionTitle {
            get {
                return ResourceManager.GetString("Tax_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Tip: Check your latest payslip for exact tax rate.
        /// </summary>
        internal static string Tax_Tip {
            get {
                return ResourceManager.GetString("Tax_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax rate (%).
        /// </summary>
        internal static string TaxRate_Label {
            get {
                return ResourceManager.GetString("TaxRate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 33.
        /// </summary>
        internal static string TaxRate_Placeholder {
            get {
                return ResourceManager.GetString("TaxRate_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save theme setting.
        /// </summary>
        internal static string ThemeSaveErrorMessage {
            get {
                return ResourceManager.GetString("ThemeSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today, {0:MMMM dd, yyyy}.
        /// </summary>
        internal static string TodayDate {
            get {
                return ResourceManager.GetString("TodayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Childcare.
        /// </summary>
        internal static string VAB {
            get {
                return ResourceManager.GetString("VAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  👶.
        /// </summary>
        internal static string VABIcon {
            get {
                return ResourceManager.GetString("VABIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        internal static string Vacation {
            get {
                return ResourceManager.GetString("Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏖️ Vacation information.
        /// </summary>
        internal static string Vacation_SectionTitle {
            get {
                return ResourceManager.GetString("Vacation_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Enter your saved vacation days from your latest payslip.
        /// </summary>
        internal static string Vacation_Tip {
            get {
                return ResourceManager.GetString("Vacation_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation days per year.
        /// </summary>
        internal static string VacationDays_Label {
            get {
                return ResourceManager.GetString("VacationDays_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏖️.
        /// </summary>
        internal static string VacationIcon {
            get {
                return ResourceManager.GetString("VacationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid hourly rate.
        /// </summary>
        internal static string Validation_HourlyRate {
            get {
                return ResourceManager.GetString("Validation_HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title is required.
        /// </summary>
        internal static string Validation_JobTitleRequired {
            get {
                return ResourceManager.GetString("Validation_JobTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid monthly salary.
        /// </summary>
        internal static string Validation_MonthlySalary {
            get {
                return ResourceManager.GetString("Validation_MonthlySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        internal static string Validation_OBCategoryRequired {
            get {
                return ResourceManager.GetString("Validation_OBCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one day.
        /// </summary>
        internal static string Validation_OBDaysRequired {
            get {
                return ResourceManager.GetString("Validation_OBDaysRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the unsocial hours rule.
        /// </summary>
        internal static string Validation_OBNameRequired {
            get {
                return ResourceManager.GetString("Validation_OBNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid hourly rate.
        /// </summary>
        internal static string Validation_OBRateRequired {
            get {
                return ResourceManager.GetString("Validation_OBRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid vacation days.
        /// </summary>
        internal static string Validation_VacationDays {
            get {
                return ResourceManager.GetString("Validation_VacationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace is required.
        /// </summary>
        internal static string Validation_WorkplaceRequired {
            get {
                return ResourceManager.GetString("Validation_WorkplaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View History.
        /// </summary>
        internal static string ViewHistory {
            get {
                return ResourceManager.GetString("ViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📊 View Reports.
        /// </summary>
        internal static string ViewReports {
            get {
                return ResourceManager.GetString("ViewReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your payroll app!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your salary app!.
        /// </summary>
        internal static string WelcomeToApp {
            get {
                return ResourceManager.GetString("WelcomeToApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Days.
        /// </summary>
        internal static string WorkDays {
            get {
                return ResourceManager.GetString("WorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace.
        /// </summary>
        internal static string Workplace {
            get {
                return ResourceManager.GetString("Workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace *.
        /// </summary>
        internal static string Workplace_Label {
            get {
                return ResourceManager.GetString("Workplace_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Municipality.
        /// </summary>
        internal static string Workplace_Placeholder {
            get {
                return ResourceManager.GetString("Workplace_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work shift .
        /// </summary>
        internal static string WorkShift {
            get {
                return ResourceManager.GetString("WorkShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🕐.
        /// </summary>
        internal static string WorkShiftIcon {
            get {
                return ResourceManager.GetString("WorkShiftIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
